---
title: "Fungicide sensitivity assessments"
bibliography: "packages.bib"
output:
  html_document
---
```{r global_options, include=FALSE}
knitr::opts_chunk$set(fig.width=6.5, fig.height=5,
                      echo=FALSE, warning=FALSE, message=FALSE)

```

# Load packages
```{r libs, warning = FALSE, message= FALSE}
list.of.packages <-
  c(
    "dplyr",
    "tidyr",
    "ggplot2",
    "knitr",
    "readxl",
    "egg",
    "car",
    "emmeans",
    "effects",
    "multcomp",
    "broom",
    "dotwhisker",
    "broom.mixed",
    "agricolae",
    "ggpubr",
    "ggplot2",
    "knitr",
    "here",
    "PerformanceAnalytics",
    "readxl",
    "Hmisc",
    "GGally",
    "corrplot"
  )

new.packages <-
  list.of.packages[!(list.of.packages %in% installed.packages()[, "Package"])]

#Download packages that are not already present in the library
if (length(new.packages))
  install.packages(new.packages)

packages_load <-
  lapply(list.of.packages, require, character.only = TRUE)

#Print warning if there is a problem with installing/loading some of packages
if (any(as.numeric(packages_load) == 0)) {
  warning(paste("Package/s: ", paste(list.of.packages[packages_load != TRUE], sep = ", "), "not loaded!"))
} else {
  print("All packages were successfully loaded.")
}

#Save list of packages used in the analysis
saveRDS(list.of.packages, here::here(paste0("ref/fungsens_packages.rds")))

        
list.of.packages

rm(list.of.packages, new.packages, packages_load)

#if instal is not working try 
#install.packages("ROCR", repos = c(CRAN="https://cran.r-project.org/"))
```
# Import data
```{r importdata, warning = FALSE, message= FALSE}
dta <- read_excel("dta/Fungicide.xlsx", 
                sheet = "Sheet1",
                col_types = c("text", "text", "text", "numeric"))
summary(dta)
dta <- 
  pivot_wider(dta, names_from  = "Chemical", values_from = "EC50" )
```
# Fitting models
```{r}
one.way <- aov(APN ~ Year, data = dta)

summary(one.way)

par(mfrow=c(2,2))
plot(one.way)
par(mfrow=c(1,1))
```
```{r}
tukey.one.way<-TukeyHSD(one.way)

tukey.one.way
```
```{r}
tukey.plot.aov<-aov(APN ~ Year, data=dta)
```
```{r}
tukey.plot.test<-TukeyHSD(tukey.plot.aov)
plot(tukey.plot.test, las = 1)
```

```{r}
tukey.one.way <- TukeyHSD(one.way, Year = 'group')
tukey.one.way
```
```{r}
(hsd<-HSD.test(one.way, "Year"))

GetLetters <- function(df, group, fit){
df_letters <- df$groups
df_letters$Chemical <- group
df_letters[,group] <-NULL
df_letters$Year <- rownames(df_letters)

# broom.mixed::tidy(fit, conf.int = TRUE)

return(df_letters)
}
df_let <- GetLetters(hsd, "APN")

```
 
Fenpicoxamid
```{r}
one.way <- aov(FNX ~ Year, data = dta)

summary(one.way)

par(mfrow=c(2,2))
plot(one.way)
par(mfrow=c(1,1))
```

```{r}
tukey.one.way<-TukeyHSD(one.way)

tukey.one.way
```
```{r}
tukey.plot.aov<-aov(FNX ~ Year, data=dta)
```
```{r}
tukey.plot.test<-TukeyHSD(tukey.plot.aov)
plot(tukey.plot.test, las = 1)
```
```{r}
hsd<-HSD.test(one.way, "Year")
hsd
```

```{r}
df_let <- bind_rows(df_let,GetLetters(hsd, "FNX"))
```

```{r}
one.way <- aov(FLX ~ Year, data = dta)

summary(one.way)

par(mfrow=c(2,2))
plot(one.way)
par(mfrow=c(1,1))
```

```{r}
tukey.one.way<-TukeyHSD(one.way)

tukey.one.way
```
```{r}
tukey.plot.aov<-aov(FLX ~ Year, data=dta)
```
```{r}
tukey.plot.test<-TukeyHSD(tukey.plot.aov)
plot(tukey.plot.test, las = 1)
```

```{r}
hsd<-HSD.test(one.way, "Year")
hsd

```
```{r}
df_let <- bind_rows(df_let,GetLetters(hsd, "FLX"))

```

```{r}
one.way <- aov(MFZ ~ Year, data = dta)

summary(one.way)

par(mfrow=c(2,2))
plot(one.way)
par(mfrow=c(1,1))
```

```{r}
tukey.one.way<-TukeyHSD(one.way)

tukey.one.way
```

```{r}
tukey.plot.aov<-aov(MFZ ~ Year, data=dta)
```
```{r}
tukey.plot.test<-TukeyHSD(tukey.plot.aov)
plot(tukey.plot.test, las = 1)
```

```{r}
hsd<-HSD.test(one.way, "Year")
hsd
```

```{r}
df_let <- bind_rows(df_let,GetLetters(hsd, "MFZ"))

```


```{r}
one.way <- aov(PDZ ~ Year, data = dta)

summary(one.way)

par(mfrow=c(2,2))
plot(one.way)
par(mfrow=c(1,1))
```

```{r}
tukey.one.way<-TukeyHSD(one.way)

tukey.one.way
```

```{r}
tukey.plot.aov<-aov(PDZ ~ Year, data=dta)
```
```{r}
tukey.plot.test<-TukeyHSD(tukey.plot.aov)
plot(tukey.plot.test, las = 1)
```

```{r}
hsd<-HSD.test(one.way, "Year")
hsd
```

```{r}
df_let <- bind_rows(df_let,GetLetters(hsd, "PDZ"))

```

```{r}
one.way <- aov(TBZ ~ Year, data = dta)

summary(one.way)

par(mfrow=c(2,2))
plot(one.way)
par(mfrow=c(1,1))
```
```{r}
tukey.one.way<-TukeyHSD(one.way)

tukey.one.way
```
```{r}
tukey.plot.aov<-aov(PDZ ~ Year, data=dta)
```
```{r}
tukey.plot.test<-TukeyHSD(tukey.plot.aov)
plot(tukey.plot.test, las = 1)
```

```{r}
hsd<-HSD.test(one.way, "Year")
hsd
```



```{r}
df_let <- bind_rows(df_let,GetLetters(hsd, "TBZ"))

```

Convert the data in longer format. 
```{r}
dta <- 
  pivot_longer(dta, cols = c("APN","FNX","FLX","MFZ","PDZ","TBZ"),
             names_to = "Chemical",
             values_to = "EC50")
```

# Publication plot
Prepare the data for plotting. 

```{r}
plotdata <- 
  df_let %>% 
left_join(dta, df_let, by = c("Year", "Chemical")) %>% 
  mutate_if(sapply(., is.character), as.factor) %>% 
  group_by(Year, Chemical) %>% 
  mutate(letter_height = max(EC50, na.rm = TRUE)) %>%
  ungroup() %>%
  mutate(Chemical = ifelse(Chemical %in% c("MFZ","PDZ","TBZ"), paste(Chemical,"(Azole)"),
                           ifelse(Chemical %in% c( "APN","FLX"),paste(Chemical,"(SHDI)"),
                                  ifelse( Chemical== "FNX", paste(Chemical, "(QiI)"),Chemical))
  )
  )
```

Plot in one row. 

```{r}
plotdata %>% 
  ggplot( aes(Year, EC50, colour = Year)) +
  geom_jitter(size=0.5, alpha=0.3,width = 0.2) +
  stat_summary(fun.data = 'mean_se', geom = 'errorbar', width = 0.3, colour = "black") +
  stat_summary(fun.data = 'mean_se', geom = 'pointrange',size = .1 ,colour = "black") +
  geom_text(aes(label = groups, y = letter_height + .4, x = Year),
            size = 3.5, colour = "black") +
  facet_wrap(~Chemical, nrow = 1)+
  
  xlab("Isolate collection")+
  ylab("Sensitivity") +
  labs(color = "Year:") +
  egg::theme_article()+
  # coord_equal(6 / 2) +
    scale_color_brewer(palette = "Dark2")+

  scale_y_continuous(limits = c(-3, 2.4)) +
  theme(text = element_text(size = 11),
        legend.position = "top",
        axis.text.x = element_text(angle = 40, vjust = 0.9, hjust=.9),
        axis.text.y = element_text(size= 7.5)) +
  guides(colour = guide_legend(override.aes = list(size=3)))+
  ggsave(
    here::here("res", "final_fungicide_plot_horisontal.png"),
    width = 8,
    height = 4.5,
    dpi =500,
    limitsize = F
  ) 

```
  
  Plot in two rows. 
  
```{r}
plotdata %>% 
  ggplot( aes(Year, EC50, colour = Year)) +
  geom_jitter(size=0.5, alpha=0.3,width = 0.2) +
  stat_summary(fun.data = 'mean_se', geom = 'errorbar', width = 0.5, colour = "black") +
  stat_summary(fun.data = 'mean_se', geom = 'pointrange',size = .1 ,colour = "black") +
  geom_text(aes(label = groups, y = letter_height + .4, x = Year),
            size = 3.5, colour = "black") +
  facet_wrap(~Chemical)+
  scale_color_brewer(palette = "Dark2")+
  xlab("Isolate collection")+
  ylab("Sensitivity") +
  labs(color = "Year:") +
  egg::theme_article()+
  # coord_equal(6 / 2) +
  scale_y_continuous(limits = c(-3, 2.4)) +
  theme(text = element_text(size = 11.5),
        legend.position = "top") +
  guides(colour = guide_legend(override.aes = list(size=3)))+
  ggsave(
    here::here("res", "final_fungicide_plot.png"),
    width = 5.3,
    height = 6,
    dpi =500,
    limitsize = F
  ) 
```

# Cross-resistance between fungicides 

```{r}
dta <- 
  pivot_wider(dta, names_from  = "Chemical", values_from = "EC50" )
dta <- dta[c("APN","FNX","FLX","MFZ","PDZ","TBZ")]
```

# Correlation charts
```{r}
chart.Correlation(dta)
```

```{r}
cor.dta <- cor(dta, method = c("spearman"))
cor.dta1 <- rcorr(cor.dta, type = "spearman")
str(cor.dta1)
```


```{r}
png(filename = "res/scatterplot.png")
plot(dta, pch=20, cex=0.5, col="4", order=NULL, upper.panel=NULL, main="Cross-Resistance")
dev.off()
```

```{r}
mycor <- rcorr(as.matrix(dta), type = "spearman")
          mycor$r
          mycor$P
```


```{r}
ggcorr(dta, label = TRUE,label_round = 2, method = c("everything", "spearman" ))
ggsave(here::here("res", "correlationplot.png"))

```


```{r }
# mat : is a matrix of data
# ... : further arguments to pass to the native R cor.test function
cor.mtest <- function(mat, ...) {
  mat <- as.matrix(mat)
  n <- ncol(mat)
  p.mat <- matrix(NA, n, n)
  diag(p.mat) <- 0
  for (i in 1:(n - 1)) {
    for (j in (i + 1):n) {
      tmp <- cor.test(mat[, i], mat[, j], ...)
      p.mat[i, j] <- p.mat[j, i] <- tmp$p.value
    }
  }
  colnames(p.mat) <- rownames(p.mat) <- colnames(mat)
  p.mat
}
# matrix of the p-value of the correlation
p.mat <- cor.mtest(dta)
p.mat



```

# Publication plot
```{r}
col <-
  colorRampPalette(c("#BB4444", "#EE9988", "#FFFFFF", "#77AADD", "#4477AA"))

png(here("res", "correlation_pairs_plot_significance.png"))
corrplot(
  cor.dta,
  method = "color",
  col = col(200),
  type = "upper",
  # order="hclust",
  addCoef.col = "black",
  tl.col = "black",
  number.cex = 1.1,
  tl.cex = 1.1,
  tl.srt = 0,
  tl.offset = 1.1,
  #Significance 
  p.mat = p.mat,
  sig.level = 0.05,
  insig = "blank" #change here to get different options for significance
)


dev.off()
```



