% About
---
bibliography: "ref/packages.bib"
csl: biomed-central.csl
---

This repository is the analysis for  the manuscript entitled: Detection of virulence to septoria tritici blotch (STB) resistance conferred by the winter wheat cultivar Cougar in the Irish *Zymoseptoria tritici* population and potential implications for STB control.  
  
**The open-access publication of the manuscript can be found** 


The funding for this project comes from [Teagasc ](https://www.teagasc.ie/) (Agriculture and Food Development Authority)(project code 0154)  . 

## Notes 

Some code chunks are folded and they can be accessed by clicking on the arrow (The code).  
Try not to have other R sessions running because it could produce problems installing libraries.  
If there are any problems reproducing the analysis, please submit an issue on GitHub.  

## Project team

Maynooth University:  
- [Stephen Kildea](https://www.teagasc.ie/contact/staff-directory/k/stephen-kildea/)

- [Liam Sheppard](https://www.teagasc.ie/contact/staff-directory/s/liam-sheppard/)

- [Mladen Cucak](https://plantpath.psu.edu/directory/mbc5867)

- [Fiona Hutton](https://www.teagasc.ie/contact/staff-directory/h/fiona-hutton/)


## Packages used in the analysis

```{r echo=F}
library(tidyverse)
pckgs <- 
lapply(list.files(here::here("ref"), full.names = T, pattern = ".rds"), readRDS) %>% 
  flatten_chr() %>%
  unique()

knitr::write_bib(c(pckgs, "bookdown"), "ref/packages.bib")
```




## Licences

Data: [CC-0](https://creativecommons.org/publicdomain/zero/1.0/) attribution requested in reuse
Manuscript: [CC-BY-4.0](https://creativecommons.org/licenses/by/4.0/)  
Code: [MIT](https://opensource.org/licenses/MIT) year: 2019, copyright holder: Mladen Cucak

## Contributions

We welcome contributions from everyone. Before you get started, please see our [contributor guidelines](CONTRIBUTING.html). Please note that this project is released with a [Contributor Code of Conduct](CONDUCT.html). By participating in this project you agree to abide by its terms.

# References

Auguie B, 2019. egg: Extensions for ggplot2: Custom Geom, Custom Themes, Plot Alignment, Labelled Panels, Symmetric Scales, and Fixed Panel Size.
Bolker B, Robinson D, 2020. broom.mixed: Tidying Methods for Mixed Models.
Brooks ME, Kristensen K, Benthem KJ van et al., 2017. glmmTMB Balances Speed and Flexibility Among Packages for Zero-inflated Generalized Linear Mixed Modeling. The R Journal 9, 378–400.
Fox J, 2003. Effect Displays in R for Generalised Linear Models. Journal of Statistical Software 8, 1–27.
Fox J, Hong J, 2009. Effect Displays in R for Multinomial and Proportional-Odds Logit Models: Extensions to the effects Package. Journal of Statistical Software 32, 1–24.
Fox J, Weisberg S, 2018. Visualizing Fit and Lack of Fit in Complex Regression Models with Predictor Effect Plots and Partial Residuals. Journal of Statistical Software 87, 1–27.
Fox J, Weisberg S, 2019. An R Companion to Applied Regression. Thousand Oaks CA: Sage.
Fox J, Weisberg S, Price B, 2020a. car: Companion to Applied Regression.
Fox J, Weisberg S, Price B, Friendly M, Hong J, 2020b. effects: Effect Displays for Linear, Generalized Linear, and Other Models.
Harrell FE Jr, 2021. Hmisc: Harrell Miscellaneous.
Hothorn T, Bretz F, Westfall P, 2008. Simultaneous Inference in General Parametric Models. Biometrical Journal 50, 346–363.
Iannone R, Cheng J, Schloerke B, 2020. gt: Easily Create Presentation-Ready Display Tables.
Kassambara A, 2020. ggpubr: ggplot2 Based Publication Ready Plots.
Lenth RV, 2020. emmeans: Estimated Marginal Means, aka Least-Squares Means.
Lüdecke D, 2021. sjPlot: Data Visualization for Statistics in Social Science.
Magnusson A, Skaug H, Nielsen A et al., 2020. glmmTMB: Generalized Linear Mixed Models using Template Model Builder.
Mendiburu F de, 2020. agricolae: Statistical Procedures for Agricultural Research.
Müller K, 2020. here: A Simpler Way to Find Your Files.
Peterson BG, Carl P, 2020. PerformanceAnalytics: Econometric Tools for Performance and Risk Analysis.
Robinson D, Hayes A, Couch S, 2020. broom: Convert Statistical Objects into Tidy Tibbles.
Schloerke B, Cook D, Larmarange J et al., 2021. GGally: Extension to ggplot2.
Solt F, Hu Y, 2018. dotwhisker: Dot-and-Whisker Plots of Regression Results.
Thoen E, 2020. padr: Quickly Get Datetime Data Ready for Analysis.
Wei T, Simko V, 2017. corrplot: Visualization of a Correlation Matrix.
Wickham H, 2016. ggplot2: Elegant Graphics for Data Analysis. Springer-Verlag New York.
Wickham H, 2020. tidyr: Tidy Messy Data.
Wickham H, Averick M, Bryan J et al., 2019. Welcome to the tidyverse. Journal of Open Source Software 4, 1686.
Wickham H, Bryan J, 2019. readxl: Read Excel Files.
Wickham H, Chang W, Henry L et al., 2020a. ggplot2: Create Elegant Data Visualisations Using the Grammar of Graphics.
Wickham H, François R, Henry L, Müller K, 2021. dplyr: A Grammar of Data Manipulation.
Wickham H, Hester J, Chang W, 2020b. devtools: Tools to Make Developing R Packages Easier.
Xie Y, 2014. knitr: A Comprehensive Tool for Reproducible Research in R. In: Stodden V,, Leisch F,, Peng RD, eds. Implementing Reproducible Computational Research. Chapman and Hall/CRC,.
Xie Y, 2016. bookdown: Authoring Books and Technical Documents with R Markdown. Boca Raton, Florida: Chapman and Hall/CRC.

